### ISSUE TITLE
Unable to generate the project structure

### ISSUE THREAD

**Issue by reflexdemon** [rustydevs/generator-awesome-webpack-starter#2]
While generating project we are getting the bellowing error.

command used:
```
❯ yo awesome-webpack-starter

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Rusty   │
    |--(o)--|    │           Dev's          │
   `---------´   │ generator-awesome-webpac │
    ( _´U`_ )    │   k-starter generator!   │
    /___A___\   /╰──────────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

events.js:182
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-awesome-webpack-starter/generators/app/templates/.gitignore
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-awesome-webpack-starter/node_modules/mem-fs-editor/lib/actions/copy.js:47:3)
    at module.exports.writing (/usr/local/lib/node_modules/generator-awesome-webpack-starter/generators/app/index.js:33:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-awesome-webpack-starter/node_modules/yeoman-generator/lib/index.js:417:23)
    at /usr/local/lib/node_modules/generator-awesome-webpack-starter/node_modules/run-async/index.js:25:25
    at Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-awesome-webpack-starter/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-awesome-webpack-starter/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

Node and npm version:
```
❯ node -v                                                                                                                                         ⏎
v8.1.2

❯ npm -v
5.0.3
```

**Comment by reflexdemon** [comment]
generator-awesome-webpack-starter@1.0.2 has the fix
